apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: db
  name: db
spec:
  selector:
    matchLabels:
      component: db
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: db
    spec:
      containers:
        - name: db
          image: postgres:11.2
          ports:
            - containerPort: 5432
          args:
            # - --transaction-isolation=READ-COMMITTED
            # @TODO: nikola - SETUP REPLICATION
            # - --binlog-format=ROW
            - --max-connections=1000
          env:
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DATABASE
                  name: db-secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: db-secrets
            - name: POSTGRES_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_ROOT_PASSWORD
                  name: db-secrets
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: db-secrets
          volumeMounts:
            - mountPath: /var/lib/postgres
              name: db-persistent-storage
      restartPolicy: Always
      volumes:
        - name: db-persistent-storage
          persistentVolumeClaim:
            claimName: db-pvc
