apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  POSTGRES_DATABASE: bmV4dGNsb3Vk  #nextcloud
  POSTGRES_USER: bmV4dGNsb3Vk      #nextcloud
  POSTGRES_PASSWORD: bmV4dGNsb3Vk      #nextcloud
  POSTGRES_ROOT_PASSWORD: bmV4dGNsb3Vk      #nextcloud
